runtime: python39
entrypoint: gunicorn -b :$PORT app:app --timeout 300 --workers 2 --threads 4 --max-requests 1000

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: 5000ms
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

env_variables:
  PYTHONUNBUFFERED: "1"
  # Reduce memory usage for BeautifulSoup
  PYTHONSETUPTOOLS_UNSAFE: "1"